contact_links:
  - about: Get support on the Profit Discord server.
    name: Join the official Discord server
    url: 'https://discord.gg/wVAd75mJYR'
  - about: Get support on the Chia Keybase chat channels.
    name: Join the Zombie Forks Discord server
    url: 'https://discord.gg/ZjrVm9SFJk'
