contact_links:
  - name: Profit official Discord server
    about: Support from the official developers
    url: 'https://discord.gg/wVAd75mJYR'
  - name: Zombie Forks Discord server
    about: Support from the developers of this client
    url: 'https://discord.gg/ZjrVm9SFJk'
